import image1 from '~/lib/tutorial/image1.png';

export default function Interface() {
  return (
    <div className="px-4 **:my-4 text-sm">
      <h2 className="text-2xl font-semibold">Interface Overview</h2>
      <p>The NeoDev environment is divided into four high-level functional areas, each serving a specific stage of the development lifecycle.</p>

      <h3 className="text-xl font-medium mt-6 text-indigo-600">1. The Playground</h3>
      <p>The Playground is an infinite vector canvas where the project structure is defined. It utilizes a "Frame-based" hierarchy:</p>
      <ul className="list-disc ml-8">
        <li><strong>Frames:</strong> Discrete containers that act as logical groupings (similar to `&lt;section&gt;` or `&lt;div&gt;` tags).</li>
        <li><strong>Blocks:</strong> The atomic units of content (Text, Images, Links) that reside inside Frames.</li>
      </ul>

      <h3 className="text-xl font-medium mt-6 text-indigo-600">2. Preview Panel</h3>
      <p>The Preview Panel provides a real-time, high-fidelity render of the project. It mirrors how the Frames in the <strong>Main Frame</strong> will appear on a standard browser, updating instantly as Blocks are rearranged or styled.</p>

      <h3 className="text-xl font-medium mt-6 text-indigo-600">3. Info Panel</h3>
      <p>This panel provides granular control and data visualization through two modules:</p>
      <ul className="list-disc ml-8">
        <li><strong>Properties:</strong> The inspector for the currently selected Block (e.g., editing text content, link URLs, or metadata).</li>
        <li><strong>Code View:</strong> A read-only preview of the production-ready code generated by your visual layout.</li>
      </ul>
    </div>

  );
}